general {
    lock_cmd = hyprlock
    before_sleep_cmd = hyprlock
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_wayland_inhibit = false
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

# Lock after 3 minutes
listener {
    timeout = 180
    on-timeout = hyprlock
}

# Turn screen off shortly after
listener {
    timeout = 200
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
