[opener]
image = [
    { run = 'feh "$@"', orphan = true, desc = "Feh" }
]
media = [
    { run = 'mpv "$@"', orphan = true, desc = "MPV" }
]
pdf = [
    { run = 'zathura "$@"', orphan = true, desc = "Zathura" }
]
epub = [
    { run = 'kitty --class floating epy "$@"', orphan = true, desc = "Epy" }
]
text = [
    { run = 'kitty --class floating nvim "$@"', orphan = true, desc = "nvim" }
]

google = [
    { run = '/home/daya/.dotfiles/scripts/open-in-gdocs.sh "$@"', orphan = true, desc = "Google Workspace" }
]

office = [
    {run = '/home/daya/.dotfiles/scripts/open-in-office "$@"', orphan = true, desc = "MS Office"}
]

torrent = [
    { run = 'transmission-gtk "$@"', orphan = true, desc = "Torrent (Transmission)" }
]
browser = [
    { run = 'zen-browser "$@"', orphan = true, desc = "Browser" }
]

[open]
rules = [
    { mime = "image/*", use = "image" },
    { mime = "video/*", use = "video" },
    { mime = "audio/*", use = "audio" },
    { mime = "application/pdf",              use = ["pdf", "browser"]},
    { mime = "application/x-pdf",            use = "browser" },
    { mime = "application/epub+zip",         use = "epub" },
    # Word
    { mime = "application/msword",           use = "document" },
    { mime = "application/openxmlformats-officedocument.wordprocessingml.document", use = ["google","office"] },
    # Excel
    { mime = "application/vnd.ms-excel",     use = "spreadsheet" },
    { mime = "application/openxmlformats-officedocument.spreadsheetml.sheet", use = ["google","office"] },
    # PowerPoint
    { mime = "application/vnd.ms-powerpoint", use = "presentation" },
    { mime = "application/openxmlformats-officedocument.presentationml.presentation", use = ["google","office"] },
    # Torrent
    { mime = "application/x-bittorrent",     use = "torrent" },
    # Web (before text/*)
    { mime = "text/html",                    use = "browser" },
    { mime = "application/xhtml+xml",        use = "browser" },
    # Text / code
    { mime = "text/*",                       use = "text" },
    { mime = "application/json",             use = "text" },
    { mime = "application/xml",              use = "text" },
    { mime = "application/javascript",       use = "text" },
    { mime = "application/x-shellscript",    use = "text" },
    { mime = "application/x-sh",             use = "text" },
]
